config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'top/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "top#index"

  resources :users do
    member do
      get :info
    end
  end
  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    attachment :product_image
    mount_uploader :product_image, ProductImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  mount_uploader :img_name, ImgNameUploader
end

app/models/user_product.rb
class UserProduct < ApplicationRecord
    belongs_to :user_id, class_name: "User"
    belongs_to :product_id, class_name: "Product"

    enum status: { like: 0, dislike: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
  
    protected

    def after_sign_in_path_for(resource) 
        products_path
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: %i(name self_introduction sex img_name))
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index  
        @products = Product.all
    end
    def show
    end

    private 
    def product_params
        params.require(:product).permit(:brand_id, :product_name, :product_image, :price, :brand_name)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
    end
    def create
    end
    def index
    end
    def show
        @user = User.find(params[:id])
    end
    def edit
        @user = User.find(params[:id])
    end
    def destroy
    end
    def info
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to info_user_path(current_user)
    end

    private 
    def user_params
        params.require(:user).permit(:name, :profile_image, :self_introduction, :sex)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clother</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
  </head> 
  <body>
     <% if user_signed_in? %>
        <header>
          <%= link_to products_path do %>
            <%= image_tag('clother-logo-fixed.png', class: "img-circle pull-left corpolate-logo", style: "height: 20px; width: 105.2px;") %>
          <% end %>
          <input type="text1" placeholder="絞り込みをする" class="search-key">
          <ul　class="header-menu">
            <%= link_to products_path do %>
               <i class="fas fa-home fa-large"></i>
            <% end %>
            <%= link_to user_path(current_user) do %>
               <i class="fas fa-user fa-large"></i>
            <% end %>
          </ul>

        </header>
     <% end %>
     <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
     <% end %>
     <% if flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
     <% end %>
     <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.min.css">
  <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="https://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.min.js"></script>
  <%= javascript_pack_tag 'hello_vue' %>
</head>
<body>
  <div class="productsindex">
    <div id="container1">
      <% @products.each do |product| %>
        <div class="buddy" style="display: block;">
          <div class="avatar" style="display: block;">
            <transition-group name="flip">
              <div class="productsImage"><%= image_tag product.product_image.url(:thumb) %></div>
            </transition-group>
            <div class="productsContainer">
              <div class="brandName"><%= product.brand_name %></div>
              <div class="userName1"><%= product.product_name %></div>
              <div class="price"><%= product.price %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <script>
      $(document).ready(function(){

        $(".buddy").on("swiperight",function(){
          $(this).addClass('rotate-left').delay(700).fadeOut(1);
          $('.buddy').find('.status').remove();

        $(this).append('<div class="status like">Like!</div>');      
          if ( $(this).is(':last-child') ) {
            $('.buddy:nth-child(1)').removeClass ('rotate-left rotate-right').fadeIn(300);
          } else {
            $(this).next().removeClass('rotate-left rotate-right').fadeIn(400);
          }
        });

        $(".buddy").on("swipeleft",function(){
          $(this).addClass('rotate-right').delay(700).fadeOut(1);
          $('.buddy').find('.status').remove();
          $(this).append('<div class="status dislike">Dislike!</div>');

        if ( $(this).is(':last-child') ) {
          $('.buddy:nth-child(1)').removeClass ('rotate-left rotate-right').fadeIn(300);
          alert('OUPS');
        } else {
          $(this).next().removeClass('rotate-left rotate-right').fadeIn(400);
        } 
        });
      });
    </script>
</div>
</body>

app/views/top/index.html.erb
<div class="top-page">
    <div class="top-background-image">
        <div class="clother-logo">
            <%= image_tag 'clother-logo-fixed-white.png', :size =>'200x38', :class => "clother-logo1" %>
        </div>
        <div class="top-center-message" style="font-size: 105px; text-align: center; margin-top: 60px; font-weight: bold; line-height: 140px; color: white;">
            個性を引き出すファッション <br>
            マッチングアプリ
        </div>
        <div class="loginPage_contents" style="text-align: center; margin-top: 80px;">
            <button class="top-login-button" style="text-align: center;">
              <%= link_to "ログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
            </button>
        </div>
        <br>
        <div class="top-corporate-login" style="text-align: center;">
            <a href="" style="color: white;">掲載企業の方はこちら</a>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="edit-view">
    <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="first-text">
        プロフィールを編集
    </div>
    <div class="form-body">
        <%= form_for(@user) do |f| %>
            <div class="form-group">
                <label>名前</label>
                    <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"名前を入力してください" %>
                <label>ひとこと</label>
                    <%= f.text_area :self_introduction, class:"form-control", id:"inputSelfIntroduction", placeholder:"例) ストリート系のファッションが好きなので、その系統のブランドをチェックしています。" %>
                <%= f.attachment_field :profile_image %>
                <div>
                    性別:
                    <%= f.label '男' %>
                    <%= f.radio_button :sex, :男 %>
                    <%= f.label '女' %>
                    <%= f.radio_button :sex, :女 %>
                </div>
            </div>                      
            <%= f.submit "変更を保存" %>
        <% end %>
    </div>
</div>

app/views/users/info.html.erb
<div class="container">
    <div class="top-prof">
        <div class="top-user-image">
            <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', class: "prof-image", fallback: "no-image.png" %>
        </div>
        <div class="top-user-name">
            <%= @user.name %>
        </div>
    </div>
    <div class="prof-detail">
        <div class="favorite-pin">
            <%= link_to user_path(current_user), class: "to-favorite-pin-button" do %>
                <i class="fas fa-heart">お気に入り</i>
            <% end %>
        </div>
        <div class="profile">
            <%= link_to info_user_path(current_user), class: "to-detail-prof-button", style: "border-top: solid 2px #000000;" do %>
                <i class="fas fa-edit">プロフィール</i>
            <% end %>
        </div>
    </div>
    <div class="prof-container">
        <% if @user.self_introduction != nil %>
            <div class="prof-comment">
                <div class="text">ひとこと</div>
                <div class="userInfo_introduction"><%= @user.self_introduction %></div>
            </div>
        <% end %>
        <div class='userAction'>
            <div class="userAction_edit userAction_common">
                <%= link_to "プロフィールを編集", edit_user_path, class: "prof" %>
            </div>
            <div class='userAction_logout userAction_common'>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "out" %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="top-prof">
        <div class="top-user-image">
            <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', class: "prof-image", fallback: "no-image.png" %>
        </div>
        <div class="top-user-name">
            <%= @user.name %>
        </div>
    </div>
    <div class="prof-detail">
        <div class="favorite-pin">
            <%= link_to user_path(current_user), class: "to-favorite-pin-button", style: "border-top: solid 2px #000000;" do %>
                <i class="fas fa-heart">お気に入り</i>
            <% end %>
        </div>
        <div class="profile">
            <%= link_to info_user_path(current_user), class: "to-detail-prof-button" do %>
                <i class="fas fa-edit">プロフィール</i>
            <% end %>
        </div>
    </div>
</div>